// <auto-generated />
using System;
using JogoDaVelhaIA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogoDaVelhaIA.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250522031228_AddDataProperty")]
    partial class AddDataProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JogoDaVelhaIA.Models.JogadaAprendida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstadoTabuleiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PosicaoEscolhida")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoTabuleiro");

                    b.ToTable("JogadasAprendidas");
                });

            modelBuilder.Entity("JogoDaVelhaIA.Models.JogadaBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EstadoTabuleiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("PosicaoEscolhida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoTabuleiro");

                    b.ToTable("JogadasBase");
                });
#pragma warning restore 612, 618
        }
    }
}
