// <auto-generated />
using System;
using JogoDaVelhIA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogoDaVelhaIA.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EstadoTabuleiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Derrota")
                        .HasColumnType("bit");

                    b.Property<bool>("Empate")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<decimal>("ValorQ")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("Vitoria")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .IsUnique();

                    b.ToTable("EstadosTabuleiro", (string)null);
                });

            modelBuilder.Entity("JogoDaVelhIA.API.Models.Entidades.HistoricoPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EstadoTabuleiroId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroJogada")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int>("PosicaoJogada")
                        .HasColumnType("int");

                    b.Property<string>("SimboloJogador")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("EstadoTabuleiroId");

                    b.HasIndex("PartidaId");

                    b.ToTable("HistoricoPartidas", (string)null);
                });

            modelBuilder.Entity("JogoDaVelhIA.API.Models.Entidades.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("JogadorVencedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Resultado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("JogoDaVelhIA.API.Models.Entidades.HistoricoPartida", b =>
                {
                    b.HasOne("EstadoTabuleiro", "EstadoTabuleiro")
                        .WithMany("HistoricoPartidas")
                        .HasForeignKey("EstadoTabuleiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JogoDaVelhIA.API.Models.Entidades.Partida", "Partida")
                        .WithMany("Historico")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoTabuleiro");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("EstadoTabuleiro", b =>
                {
                    b.Navigation("HistoricoPartidas");
                });

            modelBuilder.Entity("JogoDaVelhIA.API.Models.Entidades.Partida", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
